name: tests

on:
- push
- pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOBIN: /tmp/.bin
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.22"

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: make test

      - uses: codecov/codecov-action@v4
        with:
          file: coverage.out
