name: tests

on:
- push
- pull_request

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-20.04]
        go-version: [1.17.x]
    runs-on: ${{ matrix.platform }}
    name: integration tests
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Install Go.
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory.
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: make test-integration

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          file: coverage.out
